services:
  api:
    build:
      context: .
    container_name: fastapi_docker
    env_file:
      - .env
    ports:
      - "8083:8000"
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:14.1-alpine
    container_name: postgres_db
    env_file:
      - .env.db
    volumes:
      - subscription_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  subscription_postgres_data:
